### ISSUE TITLE
书影音全面报错

### ISSUE THREAD

**Issue by fionananna** [icue/DoubanImageWall#3]
跟前面那位友邻一样显示Error: No image to process. HTTP request may have been blocked.，只不过我试过了书/影/音都不行。
怕自己是操作失当（今天第一天下载python...），我还特意复刻了上一位友邻的代码，也是一样报错。

**Comment by icue** [comment]
你好，我刚才在本地试了，电影和音乐都还正常。
你可以尝试换 IP，或者是 fork 之后手动触发你 repo 里的[这个 action](https://github.com/icue/DoubanImageWall/actions/workflows/generate-image-wall-on-demand-for-anyone.yml) （需要输入自己的豆瓣 id） 在 GitHub 上跑跑看。
