### ISSUE TITLE
Error: No image to process. HTTP request may have been blocked.

### ISSUE THREAD

**Issue by igstranger** [icue/DoubanImageWall#5]
关闭了代理状态下，还是显示“Error: No image to process. HTTP request may have been blocked.”

**Comment by icue** [comment]
你是选了图书吗？是的话的确会报这个错。见 https://github.com/icue/DoubanImageWall/issues/1

音乐和电影，我这边在打开和关闭代理时都正常，用 action 来跑也正常。

**Comment by icue** [comment]
已修复。
