### ISSUE TITLE
Error: No image to process. HTTP request may have been blocked.

### ISSUE THREAD

**Issue by zousiyu1995** [icue/DoubanImageWall#6]
作者您好。您在issue 1中提到，出现上述报错是因为不能访问[https://book.douban.com/people/70554016/collect?sort=rating&start=0&mode=grid&tags_sort=count](https://book.douban.com/people/70554016/collect?sort=rating&start=0&mode=grid&tags_sort=count)，我试了一下，我能访问该网址。

但设置命令行参数`-m=book`，仍然出现如下Error，
```shell
> python.exe .\image_wall.py -m=book -i=70554016
Error: No image to process. HTTP request may have been blocked.
```

**Comment by icue** [comment]
感谢反馈，确实是图书页面的解析方式有问题，现已[修复](https://github.com/icue/DoubanImageWall/commit/4ea448214c0bfdf870260baa5ad50fc2b6ce44c6)。
