### ISSUE TITLE
似乎无法抓取通过小火箭（补标）功能标记的已看影视

### ISSUE THREAD

**Issue by dividedjoy** [icue/DoubanImageWall#8]

**Comment by icue** [comment]
我不太了解小火箭补标的功能。如果您在网页版的豆瓣查看“我看过的影视”那个页面，能看到使用补标功能标记的已看影视吗？它们是否和其它已看影视以同样的方式被呈现在页面上？
（这个脚本是以该页面为起点进行抓取的）

**Comment by dividedjoy** [comment]
我发现是我弄错了，补标的电影也在海报里，但是我最早补标的电影并不是出现在海报墙最后（已经开启按时间排序），或许是因为我后来修改了补标影视的星级，所以排到前面去了哈哈哈哈
